In [65]:
import numpy as np
from sklearn.datasets import load_breast_cancer, load_digits
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, multilabel_confusion_matrix
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [6]:
# breath_cancer dataset
data = load_breast_cancer()
# print(data.data)
# print(data.target)
X = data.data
Y = data.target

In [11]:
print(X.shape)
# print(Y) # Y has value 0, 1 so we use SVC - Support Vector Classification

(569, 30)

In [39]:
# 20% of data for test and 80% for training model
train_features, test_features, train_labels, test_labels = train_test_split(X, Y, test_size = 0.2, random_state = 55)
print(train_labels.shape)
print(train_features.shape)

(455,)
(455, 30)

In [44]:
model_svc = SVC(kernel = 'rbf')
model_svc.fit(train_features, train_labels)

label_predicted = model_svc.predict(test_features)
print(classification_report(test_labels, label_predicted))

              precision    recall  f1-score   support

           0       0.93      0.88      0.91        49
           1       0.91      0.95      0.93        65

    accuracy                           0.92       114
   macro avg       0.92      0.92      0.92       114
weighted avg       0.92      0.92      0.92       114

In [24]:
comparison_table = pd.DataFrame({
    'result': range(1, len(test_labels) + 1),   # 1 to 114
    'Ground Truth (Target)': test_labels,
    'SVM ที่ใช้ rbf เป็น kernel': label_predicted
})

print(comparison_table)

     result  Ground Truth (Target)  SVM ที่ใช้ rbf เป็น kernel
0         1                      0                           0
1         2                      1                           1
2         3                      1                           1
3         4                      0                           0
4         5                      1                           1
..      ...                    ...                         ...
109     110                      0                           0
110     111                      0                           0
111     112                      1                           1
112     113                      1                           1
113     114                      1                           1

[114 rows x 3 columns]

In [26]:
confusion_matrix(test_labels, label_predicted)

array([[43,  6],
       [ 3, 62]])

In [28]:
print(accuracy_score(test_labels, label_predicted))

0.9210526315789473

In [36]:
# load_digits
data = load_digits()
features = data.data
labels = data.target
print(features.shape)
print(labels.shape)

(1797, 64)
(1797,)

In [46]:
print(np.unique(labels))
print(features.min(), features.max())

[0 1 2 3 4 5 6 7 8 9]
0.0 16.0

In [45]:
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.2, random_state = 55)

In [48]:
scaler = StandardScaler()
train_features_scaled = scaler.fit_transform(train_features)
test_features_scaled = scaler.fit_transform(test_features)

In [60]:
model = SVC(kernel = 'rbf')
model.fit(train_features_scaled, train_labels)

predicted = model.predict(test_features_scaled)
print(classification_report(test_labels, predicted))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       1.00      1.00      1.00        33
           2       0.98      1.00      0.99        40
           3       1.00      0.95      0.98        44
           4       1.00      1.00      1.00        31
           5       0.96      1.00      0.98        43
           6       1.00      1.00      1.00        36
           7       1.00      1.00      1.00        44
           8       0.93      0.96      0.95        28
           9       1.00      0.94      0.97        36

    accuracy                           0.99       360
   macro avg       0.99      0.99      0.99       360
weighted avg       0.99      0.99      0.99       360

In [66]:
# cm = confusion_matrix(test_labels, predicted)
# print(cm.shape)
# tn, fp, fn, tp = cm.ravel()
#
# sensitivity = tp / (tp + fn) # all positive, how many we got
# specificity = tn / (tn + fp) # all negative, how many we got

#
# print(f"Sensitivity (Recall): {sensitivity:.4f}")
# print(f"Specificity:          {specificity:.4f}")
sensitivities = []
specificities = []
mcm = multilabel_confusion_matrix(test_labels, predicted)
for cm_i in mcm:
    tn, fp, fn, tp = cm_i.ravel()
    sensitivities.append(tp / (tp + fn))
    specificities.append(tn / (tn + fp))

avg_sensitivity = np.mean(sensitivities)
avg_specificity = np.mean(specificities)

print(f"Average Sensitivity: {avg_sensitivity:.4f}")
print(f"Average Specificity: {avg_specificity:.4f}")

Average Sensitivity: 0.9863
Average Specificity: 0.9985

In [59]:
comparison_table = pd.DataFrame({
    'result': range(1, len(test_labels) + 1),   # 1 to 114
    'Ground Truth (Target)': test_labels,
    'SVM ที่ใช้ rbf เป็น kernel': predicted
})
print(confusion_matrix(test_labels, predicted))
display(comparison_table)

[[25  0  0  0  0  0  0  0  0  0]
 [ 0 33  0  0  0  0  0  0  0  0]
 [ 0  0 40  0  0  0  0  0  0  0]
 [ 0  0  0 42  0  1  0  0  1  0]
 [ 0  0  0  0 31  0  0  0  0  0]
 [ 0  0  0  0  0 43  0  0  0  0]
 [ 0  0  0  0  0  0 36  0  0  0]
 [ 0  0  0  0  0  0  0 44  0  0]
 [ 0  0  1  0  0  0  0  0 27  0]
 [ 0  0  0  0  0  1  0  0  1 34]]

     result  Ground Truth (Target)  SVM ที่ใช้ rbf เป็น kernel
0         1                      1                           1
1         2                      6                           6
2         3                      7                           7
3         4                      9                           9
4         5                      9                           9
..      ...                    ...                         ...
355     356                      7                           7
356     357                      5                           5
357     358                      5                           5
358     359                      5                           5
359     360                      1                           1

[360 rows x 3 columns]

In [56]:
model = SVC(kernel = 'poly')
model.fit(train_features_scaled, train_labels)

predicted = model.predict(test_features_scaled)
print(classification_report(test_labels, predicted))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.97      1.00      0.99        33
           2       1.00      0.90      0.95        40
           3       1.00      0.84      0.91        44
           4       1.00      1.00      1.00        31
           5       1.00      0.93      0.96        43
           6       1.00      0.97      0.99        36
           7       1.00      0.93      0.96        44
           8       0.56      1.00      0.72        28
           9       1.00      0.86      0.93        36

    accuracy                           0.94       360
   macro avg       0.95      0.94      0.94       360
weighted avg       0.96      0.94      0.94       360

In [57]:
comparison_table = pd.DataFrame({
    'result': range(1, len(test_labels) + 1),   # 1 to 114
    'Ground Truth (Target)': test_labels,
    'SVM ที่ใช้ rbf เป็น kernel': predicted
})
print(confusion_matrix(test_labels, predicted))
display(comparison_table)

[[25  0  0  0  0  0  0  0  0  0]
 [ 0 33  0  0  0  0  0  0  0  0]
 [ 0  0 36  0  0  0  0  0  4  0]
 [ 0  0  0 37  0  0  0  0  7  0]
 [ 0  0  0  0 31  0  0  0  0  0]
 [ 0  0  0  0  0 40  0  0  3  0]
 [ 0  0  0  0  0  0 35  0  1  0]
 [ 0  0  0  0  0  0  0 41  3  0]
 [ 0  0  0  0  0  0  0  0 28  0]
 [ 0  1  0  0  0  0  0  0  4 31]]

     result  Ground Truth (Target)  SVM ที่ใช้ rbf เป็น kernel
0         1                      1                           1
1         2                      6                           6
2         3                      7                           7
3         4                      9                           9
4         5                      9                           9
..      ...                    ...                         ...
355     356                      7                           7
356     357                      5                           5
357     358                      5                           5
358     359                      5                           5
359     360                      1                           1

[360 rows x 3 columns]